/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinishAES;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Mr Khiem
 */
public class FormDSRSA extends javax.swing.JFrame {

    /**
     * Creates new form FormDSRSA
     */
    static int bitleg;
    static BigInteger ciphertext;

    static AlgorithmRSA rsa;

    public FormDSRSA() {

        initComponents();
        jProgressBar1.setStringPainted(true);
        jProgressBar1.setForeground(Color.blue);

        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);

        bitleg = Integer.parseInt((String) jComboBox1.getSelectedItem());
        rsa = new AlgorithmRSA();
        rsa.KeyRSA(bitleg);

        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public void OutputWrite(File saveLocation, BigInteger EncryptCodes, String name)
            throws FileNotFoundException {

        PrintWriter file
                = new PrintWriter(new FileOutputStream(new File(saveLocation, name)));
        file.println(EncryptCodes);
        file.close();

    }

    private File getSaveLocation() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = chooser.showSaveDialog(this);

        if (result == chooser.APPROVE_OPTION) {
            return chooser.getSelectedFile();
        } else {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jLabel4 = new JLabel();
        jComboBox1 = new JComboBox();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jButton1 = new JButton();
        jScrollPane7 = new JScrollPane();
        jTextArea1 = new JTextArea();
        jScrollPane8 = new JScrollPane();
        jTextArea2 = new JTextArea();
        jLabel19 = new JLabel();
        jButton6 = new JButton();
        jButton7 = new JButton();
        jPanel3 = new JPanel();
        jLabel7 = new JLabel();
        jTextField1 = new JTextArea();
        jLabel10 = new JLabel();
        jLabel11 = new JLabel();
        jButton4 = new JButton();
        jScrollPane10 = new JScrollPane();
        jTextArea4 = new JTextArea();
        jLabel20 = new JLabel();
        jButton8 = new JButton();
        jPanel4 = new JPanel();
        jLabel8 = new JLabel();
        jTextField2 = new JTextArea();
        jLabel13 = new JLabel();
        jLabel14 = new JLabel();
        jButton5 = new JButton();
        jScrollPane12 = new JScrollPane();
        jTextArea6 = new JTextArea();
        jLabel1 = new JLabel();
        jLabel15 = new JLabel();
        jLabel18 = new JLabel();
        jProgressBar1 = new JProgressBar();
        jButton9 = new JButton();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        jMenuItem2 = new JMenuItem();
        jMenuItem3 = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digital Signature Software");

        jPanel1.setBackground(new Color(204, 204, 204));

        jPanel2.setBackground(new Color(255, 102, 102));

        jLabel4.setText("Kích thước");
        jLabel4.setFont(new Font("Times New Roman", 0, 16));

        jComboBox1.setModel(new DefaultComboBoxModel(new String[] { "256", "512", "1024", "2048", "3072" }));
        jComboBox1.setFont(new Font("Times New Roman", 0, 16));
        jComboBox1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Khóa bí mật");
        jLabel5.setFont(new Font("Times New Roman", 0, 16));

        jLabel6.setText("Khóa công khai");
        jLabel6.setFont(new Font("Times New Roman", 0, 16));

        jButton1.setIcon(new ImageIcon(getClass().getResource("/images/vcard_key.png"))); // NOI18N
        jButton1.setText("Tạo khóa");
        jButton1.setFont(new Font("Times New Roman", 0, 16));
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new Font("Times New Roman", 0, 13)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane7.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new Font("Times New Roman", 0, 13)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane8.setViewportView(jTextArea2);

        jLabel19.setFont(new Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setIcon(new ImageIcon(getClass().getResource("/images/key_start.png"))); // NOI18N
        jLabel19.setText("Khóa");
        jLabel19.setBounds(10,10,30,30);

        jButton6.setIcon(new ImageIcon(getClass().getResource("/images/disk_black.png"))); // NOI18N
        jButton6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new ImageIcon(getClass().getResource("/images/disk_black.png"))); // NOI18N
        jButton7.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel2.setBounds(20,20,380,620);
        //jPanel2.add(jLabel19);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jScrollPane8, GroupLayout.PREFERRED_SIZE, 357, GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(44, 44, 44)
                                                                                .addComponent(jLabel19))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(jScrollPane7, GroupLayout.PREFERRED_SIZE, 357, GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(42, 42, 42)
                                                                .addComponent(jButton1)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButton6))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButton7)))))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel19)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton6)
                                        .addComponent(jLabel5))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton7)
                                        .addComponent(jLabel6))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane8, GroupLayout.PREFERRED_SIZE, 181, GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton1)
                                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new Color(153, 255, 153));

        jLabel7.setText("Đầu vào");
        jLabel7.setFont(new Font("Times New Roman", 0, 16));


        jTextField1.setLineWrap(true);
        jTextField1.setWrapStyleWord(true);
        jTextField1.setFont(new Font("Times New Roman", 0, 16));

        jLabel10.setText(" ");

        jLabel11.setText("Kết quả sau mã hóa");
        jLabel11.setFont(new Font("Times New Roman", 0, 16));

        jButton4.setIcon(new ImageIcon(getClass().getResource("/images/shield_start.png"))); // NOI18N
        jButton4.setText("Mã Hóa");
        jButton4.setFont(new Font("Times New Roman", 0, 16));
        jButton4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new Font("Times New Roman", 0, 16)); // NOI18N
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setWrapStyleWord(true);
        jScrollPane10.setViewportView(jTextArea4);

        jLabel20.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setIcon(new ImageIcon(getClass().getResource("/images/user_mature.png"))); // NOI18N
        jLabel20.setText("Người Gửi");
        jLabel20.setFont(new Font("Times New Roman", 0, 16));

        jButton8.setIcon(new ImageIcon(getClass().getResource("/images/disk_black.png"))); // NOI18N
        jButton8.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel3.setBounds(420,20,400,620);

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(jLabel20)
                                                                                .addGap(105, 105, 105))
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(jLabel11)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jButton8))
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(jLabel7)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 261, GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(10, 10, 10))))
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addComponent(jScrollPane10, GroupLayout.PREFERRED_SIZE, 305, GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(102, 102, 102)
                                                .addComponent(jButton4)))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton8)
                                        .addComponent(jLabel11))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jLabel10))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(26, 26, 26))
        );


        jPanel4.setBackground(new Color(153, 255, 153));

        jLabel8.setText("Đầu vào");
        jLabel8.setFont(new Font("Times New Roman", 0, 16));


        jTextField2.setFont(new Font("Times New Roman", 0, 16));
        jTextField2.setLineWrap(true);
        jTextField2.setWrapStyleWord(true);


        jLabel14.setText("Kết quả sau giải mã");
        jLabel14.setFont(new Font("Times New Roman", 0, 16));

        jButton5.setIcon(new ImageIcon(getClass().getResource("/images/shield_rainbow.png"))); // NOI18N
        jButton5.setText("Kiểm tra");
        jButton5.setFont (new Font("Times New Roman", 0, 16));
        jButton5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new Font("Times New Roman", 0, 15)); // NOI18N
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setWrapStyleWord(true);
        jScrollPane12.setViewportView(jTextArea6);

        jLabel1.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/images/shield_start.png"))); // NOI18N
        jLabel1.setText("Người nhận");
        jLabel1.setFont(new Font("Times New Roman", 0, 16));


        jPanel4.setBounds(840,20,400,620);

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel14))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addComponent(jButton5)))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane12, GroupLayout.PREFERRED_SIZE, 290, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(27, 27, 27))
                                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE,150, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                                .addComponent(jScrollPane12, GroupLayout.PREFERRED_SIZE, 320, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)))
                                .addComponent(jButton5)
                                .addGap(26, 26, 26))
        );


        jLabel18.setFont(new Font("Tahoma", 2, 11)); // NOI18N
        jLabel18.setForeground(new Color(255, 0, 0));


        jButton9.setIcon(new ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        jButton9.setText("RESET");
        jButton9.setBounds(1060,650,100,30);
        jButton9.setFont(new Font("Times New Roman", 0, 16));
        jButton9.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        setLayout(null);
        setSize(1280,740);
        add(jPanel2);
        add(jPanel3);
        add(jPanel4);
        add(jButton9);

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        jProgressBar1.setIndeterminate(true);

        rsa.KeyRSA(bitleg);

        jTextArea1.setText(rsa.getE().toString());
        jTextArea2.setText(rsa.getD().toString());

        rsa.setD(new BigInteger(jTextArea1.getText()));
        rsa.setE(new BigInteger(jTextArea2.getText()));

        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jProgressBar1.setMaximum(100);
        jProgressBar1.setValue(200);
        jProgressBar1.setIndeterminate(false);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        BigInteger bigInteger = new BigInteger(jTextArea1.getText());
        try {
            OutputWrite(getSaveLocation(), bigInteger, "Keyprivate.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        BigInteger bigInteger = new BigInteger(jTextArea2.getText());
        try {
            OutputWrite(getSaveLocation(), bigInteger, "Keypublic.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        bitleg = Integer.parseInt((String) jComboBox1.getSelectedItem());
        jProgressBar1.setValue(0);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jProgressBar1.setValue(0);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");
        jTextArea2.setText("");

        jTextArea4.setText("");

        jTextArea6.setText("");
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);

        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        BigInteger bigInteger = new BigInteger(jTextArea4.getText());
        try {
            OutputWrite(getSaveLocation(), bigInteger, "Encrypt.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jProgressBar1.setValue(0);
        String filename = jTextField1.getText();// change accordingly
        if ("".equals(filename)) {
            jProgressBar1.setIndeterminate(true);
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập dữ liệu đầu vào", "Thông báo", JOptionPane.ERROR_MESSAGE);
            jProgressBar1.setMaximum(200);
            jProgressBar1.setValue(0);
            jProgressBar1.setIndeterminate(false);
        } else {
            try {
                jProgressBar1.setIndeterminate(true);
                jTextArea4.setText(rsa.encrypt(filename));
                jButton8.setEnabled(true);
                jProgressBar1.setMaximum(200);
                jProgressBar1.setValue(200);
                jProgressBar1.setIndeterminate(false);
                jTextField2.setText(jTextArea4.getText());
                JOptionPane.showMessageDialog(null, "Bạn đã mã hóa thành công!");

            } catch (Exception ex) {
                Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jProgressBar1.setValue(0);
        String filename = jTextField2.getText();

        if ("".equals(filename)) {
            jProgressBar1.setIndeterminate(true);
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập dữ liệu đầu vào", "Thông báo", JOptionPane.ERROR_MESSAGE);
            jProgressBar1.setMaximum(200);
            jProgressBar1.setValue(0);
            jProgressBar1.setIndeterminate(false);
        } else {
            try {
                jProgressBar1.setIndeterminate(true);

                jTextArea6.setText(rsa.decrypt(jTextField2.getText()));
                jProgressBar1.setMaximum(200);
                jProgressBar1.setValue(200);
                jProgressBar1.setIndeterminate(false);
                if (jTextField1.getText().equals(jTextArea6.getText())) {
                    JOptionPane.showMessageDialog(null, "Giải mã đúng!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Giải mã sai", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDSRSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1, jButton4, jButton5, jButton6,jButton7, jButton8, jButton9;
    private javax.swing.JComboBox jComboBox1;
    private JLabel jLabel1, jLabel10, jLabel11, jLabel13, jLabel14, jLabel15, jLabel18,jLabel19, jLabel20,jLabel4, jLabel5,jLabel6,jLabel7,jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2,jMenuItem3;
    private javax.swing.JPanel jPanel1, jPanel2, jPanel3, jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane10,jScrollPane12,jScrollPane7,jScrollPane8;
    private javax.swing.JTextArea jTextArea1,jTextArea2,jTextArea4,jTextArea6;
    private javax.swing.JTextArea jTextField1, jTextField2;
    // End of variables declaration//GEN-END:variables
}
